# Generated by Django 4.1.1 on 2022-09-30 06:33


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(max_length=50, upload_to='photo/%y/%m/%d')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode='utf-8')),
            ],
        ),
    ]
